In [26]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

## Data manipulation & Feature engineering

In [49]:
test_data = pd.read_csv("test.csv")
train_data = pd.read_csv("train.csv")
feat = train_data.columns

print(train_data.head(10))
#mapping = {'S':1, 'C':2, 'Q':3}
#test_data['Embarked'] = [mapping[i] for i in test_data['Embarked']]
#train_data['Embarked'] = [mapping[i] for i in train_data['Embarked']]
test_data.replace(to_replace=['S', 'C', 'Q'], value=[1,2,3], inplace=True)
train_data.replace(to_replace=['S', 'C', 'Q'], value=[1,2,3], inplace=True)

test_data.replace(to_replace=['male', 'female'], value=[1,2], inplace=True)
train_data.replace(to_replace=['male', 'female'], value=[1,2], inplace=True)

# Dropping NaNs and replacing with median
test_data['Age'].fillna(test_data['Age'].dropna().median(), inplace=True)
train_data['Age'].fillna(train_data['Age'].dropna().median(), inplace=True)
test_data['Fare'].fillna(test_data['Fare'].dropna().median(), inplace=True)
train_data['Fare'].fillna(train_data['Fare'].dropna().median(), inplace=True)
test_data.fillna(0, inplace=True)
train_data.fillna(0, inplace=True)

# Adding FamilySize
test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1
train_data['FamilySize'] = train_data['SibSp'] + train_data['Parch'] + 1

# Adding IsAlone
test_data['IsAlone'] = 0
test_data.loc[test_data['FamilySize'] == 1, 'IsAlone'] = 1
train_data['IsAlone'] = 0
train_data.loc[train_data['FamilySize'] == 1, 'IsAlone'] = 1

# Extracting desired features from array 
used_feats = ['Pclass', 'Sex', 'Age', 'Fare',
              'Embarked', 'FamilySize', 'IsAlone']
# 'Ticket', 'Cabin', 'SibSp', 'Parch'
train_x = train_data[used_feats]
test_x  = test_data[used_feats]
train_y = train_data['Survived']
test_id = test_data['PassengerId']

# Features that are left
train_x.head(10)

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  FamilySize  IsAlone
0       3    1  22.0      1      0   7.2500       1.0           2        0
1       1    2  38.0      1      0  71.2833       2.0           2        0
2       3    2  26.0      0      0   7.9250       1.0           1        1
3       1    2  35.0      1      0  53.1000       1.0           2        0
4       3    1  35.0      0      0   8.0500       1.0           1        1
5       3    1   0.0      0      0   8.4583       3.0           1        1
6       1    1  54.0      0      0  51.8625       1.0           1        1
7       3    1   2.0      3      1  21.0750       1.0           5        0
8       3    2  27.0      0      2  11.1333       1.0           3        0
9       2    2  14.0      1      0  30.0708       2.0           2        0

## Training a model - Support Vector Machines

In [36]:

# Picking the best parameters

params = {'kernel': ('linear', 'rbf'), 'C': np.linspace(0.01,0.1, 20)}

model = svm.SVC()
cf = GridSearchCV(model, params, cv=5, n_jobs=-1)
cf.fit(train_x, train_y)
cf.best_params_



#model = svm.SVC(kernel='rbf', gamma=1, C=1000)
#model.fit(train_x, train_y)
#pred = model.predict(test_x)
#acc = round(model.score(train_x, train_y) * 100, 2)
#print(acc) # 0.976
# Cross validation

{'C': 0.024210526315789474, 'kernel': 'linear'}

In [37]:
model = svm.SVC(kernel='linear', C=0.0242)
model.fit(train_x, train_y)
pred = model.predict(test_x)
acc = round(model.score(train_x, train_y) * 100, 2) # Don't know what this does...
print(acc) # 0.976

78.68

{'mean_fit_time': array([0.04501185, 0.02895441, 0.06817493, 0.02430801, 0.06762671,
        0.02272654, 0.12958961, 0.02405605, 0.12351298, 0.02738976,
        0.17139697, 0.03240724, 0.16719594, 0.02593617, 0.13120065,
        0.02281418, 0.13587008, 0.0244072 , 0.13776484, 0.02407498,
        0.16894159, 0.02877078, 0.16627059, 0.02498698, 0.17185802,
        0.024125  , 0.21397295, 0.02407727, 0.20486426, 0.02356763,
        0.22764516, 0.0259706 , 0.27614479, 0.02286644, 0.30704842,
        0.02607384, 0.28843465, 0.03230572, 0.22842693, 0.02282825]),
 'std_fit_time': array([0.00704413, 0.00694943, 0.01610348, 0.00247647, 0.01211737,
        0.00109054, 0.05908278, 0.00151138, 0.0417564 , 0.00456923,
        0.09728765, 0.01012022, 0.09267753, 0.00286219, 0.05783339,
        0.00098275, 0.04604452, 0.00268628, 0.03655053, 0.00219636,
        0.05781352, 0.01042427, 0.07761406, 0.00434191, 0.06081962,
        0.00255172, 0.07115896, 0.00362867, 0.06796088, 0.00275162,
        0.08409249, 0.00406285, 0.09526511, 0.0022956 , 0.07762238,
        0.0051    , 0.12533041, 0.00781527, 0.10683105, 0.00456467]),
 'mean_score_time': array([0.00553274, 0.00906076, 0.00505447, 0.00653477, 0.0047688 ,
        0.00629129, 0.00608797, 0.00635519, 0.00578461, 0.00959582,
        0.00481648, 0.00982828, 0.00445247, 0.00694485, 0.00420141,
        0.00627999, 0.00457668, 0.00701079, 0.0044199 , 0.00704455,
        0.00462632, 0.0054637 , 0.004072  , 0.00564461, 0.00399618,
        0.00669227, 0.00437202, 0.00521188, 0.00416455, 0.00614123,
        0.00373011, 0.00625367, 0.0095202 , 0.00745215, 0.00458131,
        0.00871916, 0.00502954, 0.00967722, 0.0031352 , 0.00698824]),
 'std_score_time': array([0.00124454, 0.0053791 , 0.0008693 , 0.00035007, 0.00031811,
        0.00036089, 0.00307329, 0.00125856, 0.00149062, 0.00219588,
        0.00035504, 0.00391553, 0.00056162, 0.00115615, 0.00065186,
        0.00076633, 0.000402  , 0.00304904, 0.00119367, 0.00124738,
        0.00041601, 0.00093842, 0.00052235, 0.00146479, 0.00073675,
        0.00093651, 0.00022452, 0.0008685 , 0.00022562, 0.00125793,
        0.00080691, 0.00046784, 0.00581128, 0.00226666, 0.00035067,
        0.00562266, 0.00152603, 0.00215281, 0.00036414, 0.00398469]),
 'param_C': masked_array(data=[0.01, 0.01, 0.01473684210526316, 0.01473684210526316,
                    0.019473684210526317, 0.019473684210526317,
                    0.024210526315789474, 0.024210526315789474,
                    0.02894736842105263, 0.02894736842105263,
                    0.03368421052631579, 0.03368421052631579,
                    0.03842105263157895, 0.03842105263157895,
                    0.04315789473684211, 0.04315789473684211,
                    0.04789473684210527, 0.04789473684210527,
                    0.052631578947368425, 0.052631578947368425,
                    0.05736842105263158, 0.05736842105263158,
                    0.06210526315789474, 0.06210526315789474,
                    0.0668421052631579, 0.0668421052631579,
                    0.07157894736842106, 0.07157894736842106,
                    0.07631578947368421, 0.07631578947368421,
                    0.08105263157894736, 0.08105263157894736,
                    0.08578947368421053, 0.08578947368421053,
                    0.09052631578947369, 0.09052631578947369,
                    0.09526315789473684, 0.09526315789473684, 0.1, 0.1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.01, 'kernel': 'linear'},
  {'C': 0.01, 'kernel': 'rbf'},
  {'C': 0.01473684210526316, 'kernel': 'linear'},
  {'C': 0.01473684210526316, 'kernel': 'rbf'},
  {'C': 0.019473684210526317, 'kernel': 'linear'},
  {'C': 0.019473684210526317, 'kernel': 'rbf'},
  {'C': 0.024210526315789474, 'kernel': 'linear'},
  {'C': 0.024210526315789474, 'kernel': 'rbf'},
  {'C': 0.02894736842105263, 'kernel': 'linear'},
  {'C': 0.02894736842105263, 'kernel': 'rbf'},
  {'C': 0.03368421052631579, 'kernel': 'linear'},
  {'C': 0.03368421052631579, 'kernel': 'rbf'},
  {'C': 0.03842105263157895, 'kernel': 'linear'},
  {'C': 0.03842105263157895, 'kernel': 'rbf'},
  {'C': 0.04315789473684211, 'kernel': 'linear'},
  {'C': 0.04315789473684211, 'kernel': 'rbf'},
  {'C': 0.04789473684210527, 'kernel': 'linear'},
  {'C': 0.04789473684210527, 'kernel': 'rbf'},
  {'C': 0.052631578947368425, 'kernel': 'linear'},
  {'C': 0.052631578947368425, 'kernel': 'rbf'},
  {'C': 0.05736842105263158, 'kernel': 'linear'},
  {'C': 0.05736842105263158, 'kernel': 'rbf'},
  {'C': 0.06210526315789474, 'kernel': 'linear'},
  {'C': 0.06210526315789474, 'kernel': 'rbf'},
  {'C': 0.0668421052631579, 'kernel': 'linear'},
  {'C': 0.0668421052631579, 'kernel': 'rbf'},
  {'C': 0.07157894736842106, 'kernel': 'linear'},
  {'C': 0.07157894736842106, 'kernel': 'rbf'},
  {'C': 0.07631578947368421, 'kernel': 'linear'},
  {'C': 0.07631578947368421, 'kernel': 'rbf'},
  {'C': 0.08105263157894736, 'kernel': 'linear'},
  {'C': 0.08105263157894736, 'kernel': 'rbf'},
  {'C': 0.08578947368421053, 'kernel': 'linear'},
  {'C': 0.08578947368421053, 'kernel': 'rbf'},
  {'C': 0.09052631578947369, 'kernel': 'linear'},
  {'C': 0.09052631578947369, 'kernel': 'rbf'},
  {'C': 0.09526315789473684, 'kernel': 'linear'},
  {'C': 0.09526315789473684, 'kernel': 'rbf'},
  {'C': 0.1, 'kernel': 'linear'},
  {'C': 0.1, 'kernel': 'rbf'}],
 'split0_test_score': array([0.65921788, 0.61452514, 0.7877095 , 0.61452514, 0.79329609,
        0.60893855, 0.79888268, 0.60893855, 0.80446927, 0.58659218,
        0.80446927, 0.59217877, 0.80446927, 0.59217877, 0.80446927,
        0.58100559, 0.80446927, 0.57541899, 0.80446927, 0.57541899,
        0.80446927, 0.57541899, 0.80446927, 0.57541899, 0.80446927,
        0.57541899, 0.80446927, 0.57541899, 0.80446927, 0.57541899,
        0.80446927, 0.57541899, 0.80446927, 0.57541899, 0.80446927,
        0.57541899, 0.80446927, 0.58100559, 0.80446927, 0.58100559]),
 'split1_test_score': array([0.79213483, 0.61797753, 0.80337079, 0.61797753, 0.80337079,
        0.61797753, 0.80898876, 0.61797753, 0.80337079, 0.62359551,
        0.80337079, 0.68539326, 0.80337079, 0.69662921, 0.80337079,
        0.70224719, 0.80337079, 0.68539326, 0.80337079, 0.69101124,
        0.80337079, 0.70224719, 0.80337079, 0.71348315, 0.80337079,
        0.71348315, 0.80337079, 0.71910112, 0.80337079, 0.71910112,
        0.80337079, 0.71910112, 0.80337079, 0.71910112, 0.80337079,
        0.71910112, 0.80337079, 0.71910112, 0.80337079, 0.71910112]),
 'split2_test_score': array([0.73595506, 0.61797753, 0.78089888, 0.61797753, 0.78651685,
        0.61797753, 0.78651685, 0.61797753, 0.78651685, 0.64044944,
        0.78651685, 0.65168539, 0.78651685, 0.66292135, 0.78651685,
        0.66292135, 0.78651685, 0.66292135, 0.78651685, 0.66292135,
        0.78651685, 0.66292135, 0.78651685, 0.66292135, 0.78651685,
        0.66292135, 0.78651685, 0.66292135, 0.78651685, 0.66292135,
        0.78651685, 0.66292135, 0.78651685, 0.66292135, 0.78651685,
        0.66292135, 0.78651685, 0.66292135, 0.78651685, 0.66292135]),
 'split3_test_score': array([0.75842697, 0.61797753, 0.75280899, 0.61797753, 0.75842697,
        0.61797753, 0.75280899, 0.61797753, 0.75280899, 0.62359551,
        0.75280899, 0.62921348, 0.75280899, 0.64044944, 0.75280899,
        0.65730337, 0.75280899, 0.6741573 , 0.75280899, 0.68539326,
        0.75280899, 0.68539326, 0.75280899, 0.68539326, 0.75280899,
        0.68539326, 0.75280899, 0.68539326, 0.75280899, 0.68539326,
        0.75280899, 0.68539326, 0.75280899, 0.68539326, 0.75280899,
        0.68539326, 0.75280899, 0.68539326, 0.75280899, 0.68539326]),
 'split4_test_score': array([0.81460674, 0.61235955, 0.79213483, 0.61235955, 0.78651685,
        0.61235955, 0.78651685, 0.61235955, 0.78651685, 0.62359551,
        0.78651685, 0.64606742, 0.78651685, 0.65730337, 0.78651685,
        0.64606742, 0.78651685, 0.65730337, 0.78651685, 0.66292135,
        0.78651685, 0.66853933, 0.78651685, 0.6741573 , 0.78651685,
        0.6741573 , 0.78651685, 0.6741573 , 0.78651685, 0.67977528,
        0.78651685, 0.67977528, 0.78651685, 0.67977528, 0.78651685,
        0.68539326, 0.78651685, 0.68539326, 0.78651685, 0.68539326]),
 'mean_test_score': array([0.75206829, 0.61616345, 0.7833846 , 0.61616345, 0.78562551,
        0.61504614, 0.78674283, 0.61504614, 0.78673655, 0.61956563,
        0.78673655, 0.64090766, 0.78673655, 0.64989643, 0.78673655,
        0.64990898, 0.78673655, 0.65103886, 0.78673655, 0.65553324,
        0.78673655, 0.65890402, 0.78673655, 0.66227481, 0.78673655,
        0.66227481, 0.78673655, 0.66339841, 0.78673655, 0.664522  ,
        0.78673655, 0.664522  , 0.78673655, 0.664522  , 0.78673655,
        0.6656456 , 0.78673655, 0.66676292, 0.78673655, 0.66676292]),
 'std_test_score': array([0.05373575, 0.00232492, 0.01694559, 0.00232492, 0.01493374,
        0.00374965, 0.01894131, 0.00374965, 0.01866721, 0.0177319 ,
        0.01866721, 0.03044014, 0.01866721, 0.03414393, 0.01866721,
        0.03930833, 0.01866721, 0.03902176, 0.01866721, 0.04165998,
        0.01866721, 0.04395233, 0.01866721, 0.04656673, 0.01866721,
        0.04656673, 0.01866721, 0.04783916, 0.01866721, 0.04814366,
        0.01866721, 0.04814366, 0.01866721, 0.04814366, 0.01866721,
        0.04855038, 0.01866721, 0.04648127, 0.01866721, 0.04648127]),
 'rank_test_score': array([20, 37, 19, 37, 18, 39,  1, 39,  2, 36,  2, 35,  2, 34,  2, 33,  2,
        32,  2, 31,  2, 30,  2, 28,  2, 28,  2, 27,  2, 24,  2, 24,  2, 24,
         2, 23,  2, 21,  2, 21], dtype=int32)}

## Saving predictions

In [40]:
df_pred = pd.DataFrame({
    'PassengerId': test_id,
    'Survived': pred
})

# Saving as csv
preds = df_pred.to_csv('dbjrelind2_pred.csv', index = False)

Notes no self:

- Do metric for test preds
- Find what params are best
- Cross validation?

https://www.kaggle.com/soham1024/titanic-data-science-eda-with-meme-solution/comments